# -*- coding: utf-8 -*-
"""K4_Week8_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LCngbhjLOdyWtAOhuuAkexTDYIBqL3F

Name: P Ajay Rahul Prasad

Roll No: 20131A05K4

8) Pandas Library: Visualization

a) Write a program which use pandas inbuilt visualization to plot following graphs:

i. Bar plots

ii. Histograms

iii. Line plots

iv. Scatter plots
"""

import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.rand(15,5),columns=['A','B','C','D','E'])
df.plot.bar()

df.plot.hist(alpha=0.5)

df.plot.line(x='A',y='B')

df.plot.scatter(x='A',y='B')

"""b) Write a program to demonstrate use of groupby() method."""

import pandas as pd  
data = {'Name': ['Harry', 'Ron','Rahul', 'Hermione','Neville','Luna','Ginny'],'Percentage': [72, 98,96, 81, 87,85,99],'Course': ['Arts','B.Com','BE','M.Tech','B.SC','BE','Arts']}  
df = pd.DataFrame(data)  
print(df)
grp=df.groupby('Course')
print(grp)
print(grp.groups)

"""c) Write a program to demonstrate pandas Merging, Joining and Concatenating"""

import pandas as pd  
data = {'key':[0,1,2,3,4,5,4],'Name': ['Harry', 'Ron','Rahul', 'Hermione','Neville','Luna','Ginny']}
data2 = {'key':[0,1,2,3,4,5,6],'Percentage': [72, 98,96, 81, 87,85,99],'Course': ['Arts','B.Com','BE','M.Tech','B.SC','BE','Arts']}
df = pd.DataFrame(data) 
df1=pd.DataFrame(data2)
res=pd.merge(df,df1,on='key')
print(res)

r1=df.join(df1.set_index('key'),on='key',how='inner')
print(r1)

data = {'Name': ['Harry Potter', 'Ronald Weasley','Ajay Rahul','Hermione Granger','Neville Longbottom'],'Percentage': [72, 98,96, 81, 87],'Course': ['Arts','B.Com','BE','M.Tech','B.SC']}  
data1={'Name':['Luna Lovegood','Ginny Weasley','Seamus Finnigan'],'Percentage':[87,85,99],'Course':['B.SC','BE','Arts']}
df = pd.DataFrame(data) 
df1=pd.DataFrame(data1) 
res=pd.concat([df,df1])
print(res)
print()
res1=pd.concat([df,df1],axis=1,join='inner')
print(res1)

"""d) Creating dataframes from csv and excel files."""

import pandas as pd
df=pd.read_csv("hiring.csv")
df.head()

df=pd.read_excel('example.xlsx')
df