# -*- coding: utf-8 -*-
"""K4_Week3_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDDKz-91yC-aNbi52NrDs4UqA4xhG8sR

Name - Punnaraju Ajay Rahul Prasad

Roll No - 20131A05K4

Week-3 1) Create a numpy array from list, tuple with float type
"""

import numpy as np
List1=[1,2,3,4,5,6,7,8,9]
Tuple1=(1,2,3,4,5,6,7,8,9)
arr1=np.array(List1, dtype=float)
print(arr1)
arr2=np.array(Tuple1, dtype=float)
print(arr2)

"""Week-3 2) Python program to demonstrate slicing,integer and boolean array **indexing**"""

import numpy as np
P1 = [6345,3957,3179,6700,7363,3777,3882] # This is a list. List will have square brackets
a = np.array(P1)
print(a[3:]) #slicing
print(a[5])
print(a[a>6000])
b = a>6000
print(b) #Prints Boolean Value

"""Week-3 3) Python program to find min,max,sum and cumulative sum of array """

import numpy as np
K4 = [43,878,863,54,2,30,4,90]
arr = np.array(K4)
min_arr = np.min(arr)
max_arr = np.max(arr)
print("Min value is ",min_arr)
print("Max value is ",max_arr)
Sum = np.cumsum(arr)
print("Sum value is ",Sum)
sum = np.sum(arr)
print("sum of values is ",sum)

"""Week-3 4) Write a python program to demonstrate use of ndim, shape, size, dtype"""

import numpy as np
arr = np.array( [[ 1, 2, 3],[ 4, 5, 6]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)