# -*- coding: utf-8 -*-
"""K4_Week10_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4GyxwZZRXigSCTUBwQSN7ufzmmf9JNJ

Name: P.Ajay Rahul Prasad

Roll No: 20131A05K4

1) Write a python program to demonstrate operator overloading.
"""

print(1 + 2)
print("Ajay"+"Rahul")
print(3 * 4)
print("Jaya Hey "*4)

"""2) Write a python program to create abstract classes and abstract methods."""

from abc import ABC, abstractmethod

class Polygon(ABC):
  @abstractmethod
  def noofsides(self):
    pass
 
class Triangle(Polygon):
  def noofsides(self):
    print("I have 3 sides")
 
class Pentagon(Polygon):
  def noofsides(self):
    print("I have 5 sides")
 
class Hexagon(Polygon):
  def noofsides(self):
    print("I have 6 sides")
 
class Quadrilateral(Polygon):
  def noofsides(self):
    print("I have 4 sides")
 
R = Triangle()
R.noofsides()
 
K = Quadrilateral()
K.noofsides()
 
R = Pentagon().noofsides()
 
K = Hexagon().noofsides()