# -*- coding: utf-8 -*-
"""K4_Week13_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135VHBu-_XuPSTH_5x-qU3TUrACyIY-9P

Name: P.Ajay Rahul Prasad

Roll No: 20131A05K4

***Week 13***

(Learning Purpose)
"""

import re

rahul = "Good Boy"
x=re.search("^Good",rahul)
print(x)

"""13) a) Given an input file which contains a list of names and phone numbers separated by spaces in the following format:

i) Phone Number contains a 3- or 2-digit area code and a hyphen followed by an 8-digit number.
"""

import re
str = input()
pattern=r"[0-9]{3}[-][0-9]{8}"
pattern1=r"[0-9]{2}[-][0-9]{8}"    
match = re.match(pattern,str) 
match1 = re.match(pattern1,str)
if  match or match1: 
      print("Valid")
else:
      print("Invalid")

"""13)a)ii) Find all names having phone numbers with a 3-digit area code using regular expressions"""

import re
l=["123-123546789 Rajesh","121-9059464864 Rahul","1234-9010315733 Shaik"]

for i in l:
  pattern = "[0-9]{3}[-]"
  a = re.match(pattern,i)
  if a:
    x=re.split("\s",i)
    print(x[1])
  #else:
    #print("not a 3-digit area code")

"""3) Write a python program to check the validity of a password given by the user. The
password should satisfy the following criteria:

i) Contain at least 1 letter between a and z

ii) Contain at least 1 number between 0 and 9

iii) Contain at least 1 letter between A and Z

iv) Contain at least 1 character from $, #, @

v) Minimum length of password: 6

vi) Maximum length of password: 12
"""

import re
password=input("Enter your password: ")
flag=0
while(1):
  if(len(password)<6):
    flag=-1
    break
  elif not re.search("[a-z]", password): #checking whether atleast one from a-z is present
    flag = -1
    break
  elif not re.search("[A-Z]", password): #checking whether atleast one from A-Z is present
    flag = -1
    break
  elif not re.search("[0-9]", password): #checking whether atleast one from 0-9 is present
    flag = -1
    break
  elif not re.search("[$#@]", password): #checking whether atleast one from $,#,@ isR present
    flag = -1
    break
  elif re.search("\s", password): #checking whether spaces are present and white spaces are not valid.
    flag = -1
    break
  else:
    flag = 0 #if all of them are false, then it's a good password.
    print("You gave yourself a Valid Password. Hooray!")
    break
if flag ==-1:
    print("Well well, Try again. Gift yourself an excellent password ¯\_(ツ)_/¯")

"""4) Write a Python program to validate mobile number."""

import re
  
def isValid(MobileNo):
    Pattern = re.compile("(0|91)?v[0-9]{9}")
    return Pattern.match(MobileNo)

MobileNo = input("Enter your Mobile No: ")
if (isValid(MobileNo)): 
    print ("Valid Number")     
else:
    print ("Invalid Number")