# -*- coding: utf-8 -*-
"""K4_Week5_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nt3WW8q9qkspmE5lOdysE453LEajUZrW

Name - Punnamaraju Ajay Rahul Prasad

Roll No - 20131A05K4

```
# This is formatted as code
```

5) a) Create a white image using NumPy in Python
"""

import numpy as np
from PIL import Image
img = np.zeros([100,100,3],dtype = np.uint8)
img.fill(255)
ab = Image.fromarray(img)
ab.save('whiteframe.jpg')
print('image saved')

"""5) b) Convert a NumPy array to an image and Convert images to NumPy array"""

import numpy as np
from PIL import Image
img = np.zeros([100,100,3],dtype = np.uint8)
img[:]=[240,80,10]
ab = Image.fromarray(img)
ab.save('whatframe.jpg')
print('image saved')
img = Image.open('whatframe.jpg')
img_array = np.array(img)
print(img_array[0][0])
print(img_array.size)

"""5) c) Perform Sorting, Searching and Counting using Numpy methods:

i) Sorting
"""

import numpy as np
a=np.array([[12, 15], [10, 1]]) 
ar1= np.sort(a,axis = 0)
print(a)
print ("Along axis is zero : \n", ar1)

"""ii) Searching"""

import numpy as np
arr=np.array([1,3,5,6]) 
b=np.argwhere(arr%3==0)
print(b)

"""iii) Counting"""

a = np.count_nonzero([[0,1,7,0,0],[3,0,0,2,19]])
b = np.count_nonzero([0,1,7,0,0])
print(a)
print(b)

"""5) d) Write a program to demonstrate the use of the reshape() method."""

import numpy as np
a=np.arange(12).reshape(6,2)
b=np.arange(8).reshape(4,2)
c=np.arange(16).reshape(2,8)
print(a)
print(b)
print(c)