# -*- coding: utf-8 -*-
"""K4_Week11_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oc_YPpPxPXsWcUVJhfxEFRG5FjwrmH-x

Name - P.Ajay Rahul Prasad

Roll No: 20131A05K4

1) Write a Python program to show different ways to create Counter.
"""

from collections import Counter
print(Counter(['A','B','C','A','C','A','C']))
print(Counter({'A':6,'B':2,'C':3}))
print(Counter(A=4,B=2,C=3))

"""2) Write a Python program to demonstrate working of OrderedDict"""

from collections import OrderedDict
d=({'a':1,'b':2,'c':3,'d':4})
print("\nThis is dictionary")
for key,value in d.items():
  print(key,value)
d=OrderedDict({'a':1,'b':2,'c':3,'d':4})
print("\nThis is Ordered dictionary")
for key,value in d.items():
  print(key,value)

"""3) Write a Python program to demonstrate working of defaultdict"""

Dict = {1: 'Harry', 2: 'Ron', 3: 'Hermione'}
print("Dictionary:",Dict)
print(Dict[1])

"""4) Write a python program to demonstrate working of ChainMap"""

from collections import ChainMap
d1 = {'a': 1, 'b': 2}
d2 = {'c': 3, 'd': 4}
d3 = {'e': 5, 'f': 6}
c = ChainMap(d1, d2, d3)
print(c)