# -*- coding: utf-8 -*-
"""K4_Week6_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iqwrQjaJJ9zcE4cRw---syvcGsCExRR

Name - P.Ajay Rahul Prasad

---

Roll No: 20131A05K4

Learning and Testing Purpose⬇️ (Run this to know what does what)
"""

import pandas as pd
mydataset={
    'Cars':['BMW','Audi','Mercedes-Benz','Aston-Martin'],'Cost':[29000000,39000000,49000000,59000000] #Can give double quotes too (" ")
}
mydatfram1=pd.DataFrame(mydataset)
print(mydatfram1)
print("\n",pd.__version__,"\n") #shows version of Panda.
#Shows things
mydatfram2=pd.Series(mydataset)
print(mydatfram2)

"""**Week 6**

1) Write a python program to implement Pandas Series with labels
"""

import pandas as pd
import numpy as np
mydataset=['BMW','Audi','Mercedes-Benz','Aston-Martin']
print("Without lables\n",pd.Series(np.array(mydataset)))
print("\nWith Lables is:\n")
mylabset=pd.Series(mydataset,index=["1st Car","2nd Car","3rd Car","4th Car"])
print(mylabset)

"""2) Create a Pandas Series from a dictionary"""

import pandas as pd
mydataset={
    'Cars':['BMW','Audi','Mercedes-Benz','Aston-Martin'],'Cost':[29000000,39000000,49000000,59000000] #Can give double quotes too (" ")
}
mydatfram2=pd.Series(mydataset)
print(mydatfram2)

"""6)c)Creating a Pandas DataFrame."""

import pandas as pd
RRR=[['Alluri Seetha Rama Raju',999],['Jennifer',998],['Komaram Bheem',999]]
Freedom=pd.DataFrame(RRR,columns=('Characters', 'Importance Rate'))
print(Freedom)

"""6)d) Describe,Head,Tail"""

import pandas as pd
a=[1,2,3,4,5]
s = pd.Series(a)
dataF=pd.DataFrame(a)
print ("The original series is:")
print (s,"\n")
print ("The first two rows of the data series:")
print (s.head(2),"\n")
print("The last two rows of the data series are: ")
print(s.tail(2))
print("The Description of the data series is: ")
print(dataF.describe())