# -*- coding: utf-8 -*-
"""K4_Week4_Programs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19dxGC9mnnyVmAEvCKSds-yHz22fRV1nC

Name: P.Ajay Rahul Prasad
Roll No: 20131A05K4

Python program to find rank, determinant, and trace of an array
"""

import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
rankMat = np.linalg.matrix_rank(arr)
print("Rank of the matrix is: ",rankMat)
print("Determinant of the matrix is: ",np.linalg.det(arr))
print("Trace of the Matrix is: ",arr.trace())

"""Python program to find eigenvalues of matrices"""

import numpy as np 
Mat1 = np.array([[2, 2, 1],[1, 3, 1],[1, 2, 2]])
print("Matrix is: ")
print(Mat1)
values, vectors = np.linalg.eig(Mat1)
print("\nEigenvalues: ",values)
print("\nEigenvectors:")
print(vectors)

"""**Transpose of a Matrix**"""

import numpy as np
a=np.array([[1,2,3]]) #We use ([[1,2,3]]) instead of ([1,2,3]) to treat it as Matrix instead of vector.
print(a.T)

"""**Python program to find matrix and vector products (dot, inner, outer product), matrix exponentiation**"""

import numpy as np
Mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
Mat2=np.array([[2,3,4],[5,6,7],[8,9,1]])
print("Inner Product of Matrix is:")
print(np.inner(Mat1,Mat2))
print("Outer Product of Matrix is:")
print(np.outer(Mat1,Mat2))
print("Dot Product of Matrix is: ")
print(np.dot(Mat1,Mat2))
print("Square of the matrix is: ")
print(np.power(Mat1,2))

"""4)d) Write a pthon program to solve a linear matrix equation, or system of linear equations"""

import numpy as np
arr1=np.array([[1,45,3],[2,76,4],[3,4,87]])
arr2=np.array([21,45,64])
print("Values are :",np.linalg.solve(arr1,arr2))